In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Bai toan eliptic
### Bai toan tinh dien

$$
u(x-\Delta x, y)
= u(x,y)
- \Delta x \,\frac{\partial u}{\partial x}(x,y)
+ \frac{(\Delta x)^2}{2!}\,\frac{\partial^2 u}{\partial x^2}(x,y)
- \frac{(\Delta x)^3}{3!}\,\frac{\partial^3 u}{\partial x^3}(x,y)
+ \cdots
$$


In [3]:
def Gauss_Seidel(N_max, epsilon, A, B):
    n = len(B)
    x_old = n *[0]
    x_new = n *[0]
    err_mang = n *[100]
    err = np.max(err_mang)
    x_matrix = []
    err_matrix = []
    x_matrix.append(x_old[:])
    for q in range(N_max):
        if err > epsilon:
            for i in range(n):
                tong1 = tong2 = 0
                for j in range(i):
                    tong1 = tong1 + A[i][j] * x_new[j]
                for j in range(i+1,n):
                    tong2 = tong2 + A[i][j] * x_old[j]
                
                x_new[i] = 1 / A[i][i] * (-tong1 -tong2 + B[i])
                
                err_mang[i] = np.abs(x_new[i] - x_old[i])
        

            err = np.max(err_mang[:])

            x_matrix.append(x_new[:])
            err_matrix.append(err)

            x_old[:] = x_new[:]
        else:
            break
    return q, x_matrix, err_matrix

In [13]:
# n la chi so toi da theo truc x va y

# i la chi so chay theo x
# j la chi so chay theo y

# u(i;0) [i:0, n-1] = 0 (u1)
# u(0;j) [j:0, n-1] = 0 (u2)
# u(n-1;j)[j:0, n-1] = 0 (u3)
# u(i,n-1)[i:0,n-1] = 100 (u4)

def dieukienbien(n,u1_bien,u2_bien,u3_bien,u4_bien):
    u = np.zeros((n,n),dtype=float)
    for i in range(n): #do range chay tu 0 -> n-1
        u[0][i] = (u1_bien)
    for i in range(n):
        u[i][0] = (u2_bien)
    for i in range(n):
        u[i][n-1] = (u3_bien)
    for i in range(n):
        u[n-1][i] = (u4_bien)
    return u


u = dieukienbien(1000,1,0,0,100)

print(u)


[[  0.   1.   1. ...   1.   1.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [100. 100. 100. ... 100. 100. 100.]]
