In [11]:
import numpy as np

In [12]:
def spectral_radius(A):
    eigenvalues = np.linalg.eigvals(A)
    bankinhpho = max(abs(eigenvalues))
    if bankinhpho < 1:
        ondinh = True
        print("He on dinh")
    else:
        ondinh = False
        print("He khong on dinh")
    return bankinhpho, ondinh

In [13]:
def diag_dominant(A):
    n = A.shape[0]
    sum_row = 0
    for i in range(n):
        for j in range(n):
            if i != j:
                sum_row = sum_row + abs(A[i, j])
        if abs(A[i, i]) > sum_row:
            print("Ma tran A co troi duong cheo nghiem ngat (strictly diagonal dominant)")
            diag_dominant = 'strict'
        elif abs (A[i, i]) >= sum_row:
            print("Ma tran A co troi duong cheo (diagonal dominant)")
            diag_dominant = 'yes'
        else:
            diag_dominant = 'no'
    return diag_dominant

In [14]:
def xacdinhduong(A):
    xTAx = np.dot(np.dot(x.T, A), x)
    if xTAx > 0:
        print("Ma tran A la ma tran xac dinh duong")
        xacdinhduong = True
    else:
        print("Ma tran A khong la ma tran xac dinh duong")
        xacdinhduong = False
    return xacdinhduong

In [15]:
def matran_diag(A):
    D = np.diag(np.diag(A))
    return D
def matran_duoi(A):
    L = np.tril(A, k=-1)
    return L
def matran_tren(A):
    U = np.triu(A, k=1)
    return U

def matran_gauss_seidel(A):
    D = matran_diag(A)
    L = matran_duoi(A)
    U = matran_tren(A)
    T_gs = np.dot(np.linalg.inv(D + L), -U)
    return T_gs

def matran_jacobi(A):
    D = matran_diag(A)
    L = matran_duoi(A)
    U = matran_tren(A)
    T_jacobi = np.dot(np.linalg.inv(D), L + U)
    return T_jacobi

## Thuc hanh 1a


In [16]:
A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
])

b = np.array([0.2, -1.425, 2])

In [20]:
# Cau a
diag_dominant_bai1 = diag_dominant(A)

# Cau b
T_gs_bai1 = matran_gauss_seidel(A)

print("Ma tran T_gs: \n", T_gs_bai1)

bankinhpho_gs_bai1, ondinh_gs_bai1 = spectral_radius(T_gs_bai1)

print("Bankinhpho T_gs: ", bankinhpho_gs_bai1)

Ma tran A co troi duong cheo (diagonal dominant)
Ma tran T_gs: 
 [[ 0.     0.     1.   ]
 [ 0.     0.     0.75 ]
 [ 0.     0.    -0.625]]
He on dinh
Bankinhpho T_gs:  0.625


## Gauss-Seidel


In [18]:
def Gauss_Seidel(N_max, epsilon, A, B):
    n = len(B)
    x_old = n *[0]
    x_new = n *[0]
    err_mang = n *[100]
    err = np.max(err_mang)
    x_matrix = []
    err_matrix = []
    x_matrix.append(x_old[:])
    for q in range(N_max):
        if err > epsilon:
            for i in range(n):
                tong1 = tong2 = 0
                for j in range(i):
                    tong1 = tong1 + A[i][j] * x_new[j]
                for j in range(i+1,n):
                    tong2 = tong2 + A[i][j] * x_old[j]
                
                x_new[i] = 1 / A[i][i] * (-tong1 -tong2 + B[i])
                
                err_mang[i] = np.abs(x_new[i] - x_old[i])
        

            err = np.max(err_mang[:])

            x_matrix.append(x_new[:])
            err_matrix.append(err)

            x_old[:] = x_new[:]
        else:
            break
    return q, x_matrix, err_matrix

def luu_file(q, x_matrix, err_matrix, filename):
    so_nghiem = len(x_matrix[0])
    heading = ""
    for i in range(so_nghiem):
        label = f"x_{i+1}"
        heading = heading + f"{label:>15s} "
    with open(f"{filename}", "w", encoding="utf-8") as file:
        file.write(f"Ket qua tinh toan he phuong trinh sau {q} lan lap:\n\n")
        file.write(f"#" * 100 + "\n" + "\n")
        file.write(f"{'i':>5s}" + heading + f"{'sai_so':>20s}\n")
        for i in range(q):
            hang = f"{i+1:>5d}"
            for x in x_matrix[i]:
                hang = hang + f"{x:>15.9f} "
            hang += f"{err_matrix[i]:>20.6e}\n"
            file.write(hang)

def tinhtoan_gauss(N_max, epsilon, A, B, filename):
    q_gauss_seidel, x_matrix_gauss_seidel, err_matrix_gauss_seidel = Gauss_Seidel(N_max, epsilon, A, B)
    filename_gauss_seidel = f"{filename}_gauss_seidel.txt"
    luu_file(q_gauss_seidel, x_matrix_gauss_seidel, err_matrix_gauss_seidel, filename_gauss_seidel)

In [19]:
## Vi ma tran co ban kinh pho >1 nen khong the giai bang phuong phap Jacobi nen ta su dung Gauss-Seidel

filename = "ketqua_thuchanh1a"
epsilon = 1e-2
N_max = 1000
tinhtoan_gauss(N_max, epsilon, A, b, filename)

## Thuc hanh 1b

In [21]:
A = np.array([
    [1, 2, -2],
    [1, 1, 1],
    [2, 2, 1]
])

b = np.array([7, 2, 5])

In [28]:
T_jacobi_bai2 = matran_jacobi(A)

print("Ma tran T_jacobi: \n", T_jacobi_bai2)

bankinhpho_jacobi_bai2, ondinh_jacobi_bai2 = spectral_radius(T_jacobi_bai2)

print("Bankinhpho T_jacobi: ", bankinhpho_jacobi_bai2)

Ma tran T_jacobi: 
 [[ 0.  2. -2.]
 [ 1.  0.  1.]
 [ 2.  2.  0.]]
He on dinh
Bankinhpho T_jacobi:  1.0809840389418118e-05


## Def ham tinh Jacobi

In [27]:
def Jacobi(N_max, epsilon, A, B):
    n = len(B)
    x_old = n *[0]
    x_new = n *[0]
    err_mang = n *[100]
    err = np.max(err_mang)
    x_matrix = []
    err_matrix = []
    x_matrix.append(x_old[:]) 
    for q in range(N_max):
        if err > epsilon:
            for i in range(n):
                tong = 0
                for j in range(n):
                    if i != j:
                        tong = tong + A[i][j] * x_old[j]
                x_new[i] = 1 / A[i][i] * (-tong + B[i])
                err_mang[i] = np.abs(x_new[i] - x_old[i])

            err = np.max(err_mang)

            x_matrix.append(x_new[:])
            
            err_matrix.append(err)

            x_old[:] = x_new[:]
        else:
            break
    return q, x_matrix, err_matrix

def tinhtoan_jacobi(N_max, epsilon, A, B, filename):
    q_jacobi, x_matrix_jacobi, err_matrix_jacobi = Jacobi(N_max, epsilon, A, B)
    filename_jacobi = f"{filename}_jacobi.txt"
    luu_file(q_jacobi, x_matrix_jacobi, err_matrix_jacobi, filename_jacobi)

In [30]:
epsilon_bai2 = 1e-5
filename  = "ketqua_thuchanh1b"
tinhtoan_jacobi(N_max, epsilon_bai2, A, b, filename)

In [31]:
T_gauss_seidel_bai2 = matran_gauss_seidel(A)
print("Ma tran T_gauss_seidel: \n", T_gauss_seidel_bai2)
bankinhpho_gs_bai2, ondinh_gs_bai2 = spectral_radius(T_gauss_seidel_bai2)
print("Bankinhpho T_gauss_seidel: ", bankinhpho_gs_bai2)


Ma tran T_gauss_seidel: 
 [[ 0. -2.  2.]
 [ 0.  2. -3.]
 [ 0.  0.  2.]]
He khong on dinh
Bankinhpho T_gauss_seidel:  2.0


In [34]:
N_max_Gauss_seidel_bai2 = 25
epsilon_Gauss_seidel_bai2 = 1e-5
filename_Gauss_seidel_bai2 = "ketqua_thuchanh1b"
tinhtoan_gauss(N_max_Gauss_seidel_bai2, epsilon_Gauss_seidel_bai2, A, b, filename_Gauss_seidel_bai2)